app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:homepage

testpage:
    path: /test
    defaults:
        _controller: AppBundle:Main:testpage

form:
    path: /testform
    defaults:
        _controller: AppBundle:Pages:mytestform